### ISSUE TITLE
Add pip cache mechanism for github action workflow

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/tox-in-gh-actions#32]
https://github.com/actions/cache/blob/main/examples.md#python---pip

```yaml
- uses: actions/cache@v3
  if: startsWith(runner.os, 'Linux')
  with:
    path: ~/.cache/pip
    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-gh.txt') }}
    restore-keys: |
      ${{ runner.os }}-pip-

- uses: actions/cache@v3
  if: startsWith(runner.os, 'macOS')
  with:
    path: ~/Library/Caches/pip
    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-gh.txt') }}
    restore-keys: |
      ${{ runner.os }}-pip-

- uses: actions/cache@v3
  if: startsWith(runner.os, 'Windows')
  with:
    path: ~\AppData\Local\pip\Cache
    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-gh.txt') }}
    restore-keys: |
      ${{ runner.os }}-pip-
```
