### ISSUE TITLE
Reorganize pre-commit cache for only Linux

### ISSUE THREAD

**Issue by sadikkuzu** [sadikkuzu/tox-in-gh-actions#36]
`pythontox.yml`

before

```yaml
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
```

after

```yaml
    - uses: actions/cache@v3
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}|pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
```
